# Generated by Django 5.2.17 on 2026-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_auditlog_action_incident_auditlog_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_UPDATED', 'Application Updated'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_ASSIGNED', 'Incident Assigned'), ('INCIDENT_STATUS_CHANGED', 'Incident Status Changed')], max_length=50),
        ),
    ]
