# Generated by Django 5.2.17 on 2026-09-23 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('APPLICATION_CREATED', 'Application Created'), ('APPLICATION_UPDATED', 'Application Updated'), ('APPLICATION_STATUS_CHANGED', 'Application Status Changed'), ('INCIDENT_CREATED', 'Incident Created'), ('INCIDENT_ASSIGNED', 'Incident Assigned'), ('INCIDENT_STATUS_CHANGED', 'Incident Status Changed'), ('INCIDENT_UPDATE_ADDED', 'Incident Update Added')], max_length=50),
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='operations.incident')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
